version: '3.7'
services:
  db:
    build: ./db/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=db
    volumes:
      - ./example_pipeline/data/docker:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pipelines:
    build: ./
    depends_on:
      - db