version: '3.8'
services:
  pipelines:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=pipelines
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./example_pipeline/original/original.csv:/pipelines/example_pipeline/original/original.csv
  db:
    restart: always
    build: ./db/
    ports:
      - "5432:5432"
    healthcheck:
      test : ["CMD-SHELL", "pg_isready --username=postgres -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5